kind: Service
apiVersion: v1
metadata:
  name: egrocer-cart
  labels:
    name: egrocer-cart
spec:
  ports:
    - nodePort: 30165 
      port: 8082      
      targetPort: 8082  
      protocol: TCP
  selector:           
    app: egrocer-cart
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: egrocer-cart
spec:                
  selector:         
    matchLabels:
      app: egrocer-cart
  replicas: 3        
  template:
    metadata:
      labels:        
        app: egrocer-cart
    spec:
      containers:
        - name: egrocer-cart
          image: linjudock19/egrocer-cart
          ports:
            - containerPort: 8082                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password     
        